### ISSUE TITLE
Question regarding the data shape.

### ISSUE THREAD

**Issue by rodgdutra** [CVxTz/time_series_forecasting#2]
Hi, first, thanks for sharing the code for the transformer network application in time series data. So I read your code and notice that your `source`, `tgt_in`, and `tgt_out` all are a matrix with 3 dimensions. I started to wonder what those dimensions mean.  For instance, in LSTM applications, the 3 dimensions would mean, respectively: batch, timestamps, and features. 

With all that in mind, I want to know if you follow the same data format of the LSTM network (batch, timestamps, features). Thanks in advance!!

**Comment by CVxTz** [comment]
In tensorflow the shapes are batch, timestamps, features), however, in Pytorch the most used shapes are (timestamps, batch, features) (unless u do batch_first=True)
