### ISSUE TITLE
Missing config.js file

### ISSUE THREAD

**Issue by nextValue123** [CVxTz/time_series_forecasting#3]
Hello, I am using your code. But now I have a problem, I need to use your config.js file. You can provide it, or talk about how to write this code？

**Comment by CVxTz** [comment]
Hello
I don't remember using a fine by that name.
Can you describe the error and what file did you run ?

**Comment by Pats666** [comment]
> 

in "pipeline.sh", line 5.

**Comment by CVxTz** [comment]
Pushed
