### ISSUE TITLE
visualization.json

### ISSUE THREAD

**Issue by dahwang22** [CVxTz/time_series_forecasting#5]
Have no visualization.json file!

**Comment by YREC710** [comment]
I have the same problem

**Comment by YREC710** [comment]
And have no trained_config.json file!

**Comment by CVxTz** [comment]
Those as output files, pipeline.sh should generate them. if it does not it means that your env setup is wrong and the code crashes.
Maybe you should read the code a little bit before opening an issue, it is not that hard.

best,
