### ISSUE TITLE
Predictions 

### ISSUE THREAD

**Issue by Gman233** [CVxTz/time_series_forecasting#6]
Hi Mate

Enjoying trying out a few of your projects really helping me on my deep learning journey, I'm currently doing your Transformer time series forecast project. I've got to the part where the model has trained and saved to transformer_ts.pth. How do I make the future predictions? I'm a noob to transformers lol

Hope for a reply 
G

**Comment by CVxTz** [comment]
Hey
thanks
Should be in this file if my memory is correct -> https://github.com/CVxTz/time_series_forecasting/blob/main/time_series_forecasting/evaluation.py
